# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_treasure_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='img_url',
            field=models.ImageField(default='media/default.png', upload_to='treasure_images'),
        ),
    ]
